version: "3.7"

services:

  edge:
    container_name: edge
    image: svnedge/app:latest
    restart: unless-stopped
    ports:
      - "18080:18080"
      - "3343:3343"
    environment:
      SET_PERMS: "false"
    volumes:
      - ${PWD}/edge/.data:/home/svnedge/csvn/data

  svserve:
    container_name: svnserve
    image: garethflowers/svn-server:latest
    restart: unless-stopped
    ports:
      - "3690:3690"
    volumes:
      - ${PWD}/edge/.data/repositories:/var/opt/svn
